/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#944a00",
        "primary-container": "#e67e22",
        "on-primary": "#ffffff",
        "on-primary-container": "#502600",
        secondary: "#4e6073",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#526478",
        tertiary: "#51634c",
        "tertiary-container": "#8b9f85",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#253622",
        background: "#f8f9fa",
        "on-background": "#191c1d",
        surface: "#f8f9fa",
        "on-surface": "#191c1d",
        "surface-variant": "#e1e3e4",
        "on-surface-variant": "#564337",
        outline: "#897365",
        "outline-variant": "#dcc1b1",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-dim": "#d9dadb",
        "surface-bright": "#f8f9fa",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        "inverse-primary": "#ffb783",
        "surface-tint": "#944a00",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
      }
    },
  },
  plugins: [],
}